### ISSUE TITLE
Micro USB connector pinout reversed 

### ISSUE THREAD

**Issue by stas2k** [tmk/keyboard_converter#3]
Micro USB connector footprint on the board is mirrored causing a polarity reversal and a swap between D- and ID pins.
I have tried to correct it but could not come up with a good way to route the swapped pins.

**Comment by tmk** [comment]
Just make foot print for your component :D
Or just use ZX62R-B-5P.

**Comment by stas2k** [comment]
OK, got it! My connector is upside down compared to the one you used.
Good thing about standards is that there are so many to choose from. :D I already have the boards from JLCPCB and the connectors, so I will just do some botch wires.

BTW, thanks for providing the boards here, as soon as my X68K arrives, I will test the adapter.
